version: '3'
volumes:
  nextcloud:
  db:
services:
  app:
    image: nextcloud:17
    # image: nextcloud:18
    depends_on:
      - db
    environment:
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_HOST: db
    ports:
    - 80:80
    volumes:
    - nextcloud:/var/www/html:rw
  db:
    image: mariadb:10.4.12-bionic
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
    volumes:
    - db:/var/lib/mysql:rw